#define MICROPY_HW_BOARD_NAME "EasyKids Robot Kit"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_HW_BOARD_EASYKID 1

#define MICROPY_PY_BLUETOOTH (0)
#define MICROPY_PY_NETWORK_WLAN (0)
#define MODULE_ST7789_ENABLED (1)
